### ISSUE TITLE
Possible incompatibility with Optifabric+Optifine

### ISSUE THREAD

**Issue by arxenix** [arxenix/better-shulkers#3]
A crash was reported in the renderEntity mixin. Look into this:

```
---- Minecraft Crash Report -------- Minecraft Crash Report ----// Uh... Did I do that?
Time: 20.9.2020 19:31Description: Rendering item
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at net.minecraft.class_918.method_23179(class_918.java:256) at net.minecraft.class_918.method_4021(class_918.java:407) at net.minecraft.class_918.method_4026(class_918.java:447) at net.minecraft.class_918.method_4023(class_918.java:426) at net.minecraft.class_481.method_2468(class_481.java:847) at net.minecraft.class_481.method_2389(class_481.java:741) at net.minecraft.class_465.method_25394(class_465.java:101) at net.minecraft.class_485.method_25394(class_485.java:43) at net.minecraft.class_481.method_25394(class_481.java:677) at net.minecraft.class_757.method_3192(class_757.java:807) at net.minecraft.class_310.method_1523(class_310.java:1021) at net.minecraft.class_310.method_1514(class_310.java:654) at net.minecraft.client.main.Main.main(Main.java:215) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector renderEntity(Lnet/minecraft/class_824;Lnet/minecraft/class_2586;Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;IILnet/minecraft/class_1799;Lnet/minecraft/class_809$class_811;Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;II)Z in bettershulkers.mixins.json:BuiltinModelItemRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap bettershulkers-refmap.json at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ... 26 more

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Render threadStacktrace: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at net.minecraft.class_918.method_23179(class_918.java:256) at net.minecraft.class_918.method_4021(class_918.java:407)
-- Item being rendered --Details: Item Type: chest Registry Name: null Item Damage: 0 Item NBT: null Item Foil: falseStacktrace: at net.minecraft.class_918.method_4026(class_918.java:447) at net.minecraft.class_918.method_4023(class_918.java:426) at net.minecraft.class_481.method_2468(class_481.java:847) at net.minecraft.class_481.method_2389(class_481.java:741) at net.minecraft.class_465.method_25394(class_465.java:101) at net.minecraft.class_485.method_25394(class_485.java:43) at net.minecraft.class_481.method_25394(class_481.java:677)
-- Screen render details --Details: Screen name: net.minecraft.class_481 Mouse location: Scaled: (240, 135). Absolute: (960.000000, 540.000000) Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000
-- Affected level --Details: All players: 1 total; [class_746['AapoL'/229, l='ClientLevel', x=331.75, y=66.00, z=-101.13]] Chunk stats: Client Chunk Cache: 3721, 3025 Level dimension: minecraft:overworld Level spawn location: World: (160,66,-16), Chunk: (at 0,4,0 in 10,-1; contains blocks 160,0,-16 to 175,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1) Level time: 1348905 game time, 190915 day time Server brand: fabric Server type: Integrated singleplayer serverStacktrace: at net.minecraft.class_638.method_8538(class_638.java:616) at net.minecraft.class_310.method_1587(class_310.java:2181) at net.minecraft.class_310.method_1514(class_310.java:672) at net.minecraft.client.main.Main.main(Main.java:215) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
-- System Details --Details: Minecraft Version: 1.16.1 Minecraft Version ID: 1.16.1 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_51, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 379603608 bytes (362 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB) CPUs: 12 JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M Fabric Mods:  bettershulkers: Better Shulkers 0.1.0 fabric: Fabric API 0.16.2+build.385-1.16.1 fabric-api-base: Fabric API Base 0.1.3+12a8474c02 fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602 fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902 fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802 fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602 fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02 fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602 fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02 fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302 fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02 fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02 fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502 fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02 fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602 fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02 fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502 fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1 fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02 fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02 fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902 fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602 fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02 fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02 fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02 fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02 fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002 fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02 fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802 fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102 fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002 fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02 fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02 fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002 fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702 fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802 fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102 fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02 fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802 fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02 fabricloader: Fabric Loader 0.9.2+build.206 litematica: Litematica 0.0.0-dev.20200630.022912 malilib: MaLiLib 0.10.0-dev.21+arne.1 minecraft: Minecraft 1.16.1 mm: Manningham Mills 2.0.1 modmenu: Mod Menu 1.14.5+build.30 optifabric: Optifabric 1.1.0-beta1 org_jetbrains_annotations: annotations 20.0.0 org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0 org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0 org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0 org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0 org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9 org_slf4j_slf4j-api: slf4j-api 1.7.30 org_slf4j_slf4j-simple: slf4j-simple 1.7.30 org_zeroturnaround_zt-zip: zt-zip 1.14 replaymod: Replay Mod 1.16.1-2.4.3 worldedit: WorldEdit 7.2.0-SNAPSHOT+5234-55de7cb Launched Version: fabric-loader-0.9.2+build.206-1.16.1 Backend library: LWJGL version 3.2.2 build 10 Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.07, NVIDIA Corporation GL Caps: Using framebuffer using OpenGL 3.0 Using VBOs: Yes Is Modded: Definitely; Client brand changed to 'fabric' Type: Client (map_client.txt) Resource Packs:  Current Language: English (US) CPU: 12x AMD Ryzen 5 2600 Six-Core Processor  OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre5 OptiFine Build: 20200719-015630 Render Distance Chunks: 28 Mipmaps: 4 Anisotropic Filtering: 1 Antialiasing: 0 Multitexture: false Shaders: (internal) OpenGlVersion: 4.6.0 NVIDIA 431.07 OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2 OpenGlVendor: NVIDIA Corporation CpuCount: 12
```

**Comment by ChiefChirpa3** [comment]
I have the same issue. I just have that mod on, and every time I break a shulker box, my server crashes. It is about the same crash report.

**Comment by arxenix** [comment]
@ChiefChirpa3 if you could also upload your log to pastebin, it would be much appreciated.
