### ISSUE TITLE
Possible incompatibility with Roughly Enough Items

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [arxenix/better-shulkers#7]
I don't know for sure, but judging from exception stack trace, this mod does not play well with [Roughly Enough Items](https://github.com/shedaniel/RoughlyEnoughItems). Game crashes when right clicking crafting blocks.

<details>
  <summary>Click to expand: crash-2020-09-24_14.13.22-client.txt</summary>

```
---- Minecraft Crash Report ----
// My bad.

Time: 9/24/20, 2:13 PM
Description: Rendering screen

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.minecraft.class_918.method_23179(class_918.java:256)
	at me.shedaniel.rei.impl.ItemEntryStack.optimisedRenderBase(ItemEntryStack.java:373)
	at me.shedaniel.rei.gui.widget.EntryListWidget.renderEntries(EntryListWidget.java:192)
	at me.shedaniel.rei.gui.widget.EntryListWidget.lambda$render$6(EntryListWidget.java:268)
	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
	at me.shedaniel.rei.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:267)
	at me.shedaniel.rei.gui.ContainerScreenOverlay.renderWidgets(ContainerScreenOverlay.java:612)
	at me.shedaniel.rei.gui.ContainerScreenOverlay.method_25394(ContainerScreenOverlay.java:529)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$registerClothEvents$12(RoughlyEnoughItemsCore.java:420)
	at net.minecraft.class_437.handler$zob000$onPostDraw(class_437.java:2112)
	at net.minecraft.class_437.method_25394(class_437.java:83)
	at net.minecraft.class_465.method_25394(class_465.java:106)
	at net.minecraft.class_489.method_25394(class_489.java:66)
	at net.minecraft.class_757.method_3192(class_757.java:824)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector renderEntity(Lnet/minecraft/class_824;Lnet/minecraft/class_2586;Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;IILnet/minecraft/class_1799;Lnet/minecraft/class_809$class_811;Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;II)Z in bettershulkers.mixins.json:BuiltinModelItemRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap bettershulkers-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 30 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.minecraft.class_918.method_23179(class_918.java:256)
	at me.shedaniel.rei.impl.ItemEntryStack.optimisedRenderBase(ItemEntryStack.java:373)
	at me.shedaniel.rei.gui.widget.EntryListWidget.renderEntries(EntryListWidget.java:192)
	at me.shedaniel.rei.gui.widget.EntryListWidget.lambda$render$6(EntryListWidget.java:268)
	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
	at me.shedaniel.rei.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:267)
	at me.shedaniel.rei.gui.ContainerScreenOverlay.renderWidgets(ContainerScreenOverlay.java:612)
	at me.shedaniel.rei.gui.ContainerScreenOverlay.method_25394(ContainerScreenOverlay.java:529)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$registerClothEvents$12(RoughlyEnoughItemsCore.java:420)
	at net.minecraft.class_437.handler$zob000$onPostDraw(class_437.java:2112)
	at net.minecraft.class_437.method_25394(class_437.java:83)
	at net.minecraft.class_465.method_25394(class_465.java:106)
	at net.minecraft.class_489.method_25394(class_489.java:66)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_3871
	Mouse location: Scaled: (320, 200). Absolute: (960.000000, 600.000000)
	Screen size: Scaled: (640, 400). Absolute: (1920, 1200). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['Murtaz'/170, l='ClientLevel', x=-325.87, y=83.00, z=99.18]]
	Chunk stats: Client Chunk Cache: 1089, 750
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,75,64), Chunk: (at 0,4,0 in -16,4; contains blocks -256,0,64 to -241,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 36339 game time, 57892 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:617)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:674)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 8.1 Pro (amd64) version 6.3
	Java Version: 15, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 5163124800 bytes (4923 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xms6144m -Xmx6144m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:G1HeapRegionSize=32M -XX:MaxGCPauseMillis=50 -XX:+ParallelRefProcEnabled
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		bettershulkers: Better Shulkers 0.1.0
		carpet: Carpet Mod in Fabric 1.4.11
		carpet-extra: Carpet Extra 1.4.8
		clear-skies: Clear Skies 1.5.45
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.1
		fabric: Fabric API 0.21.0+build.407-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad95
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+74685c1495
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd695
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d695
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.8.0+c1aa8ed895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.5.0+c1aa8ed895
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced895
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced895
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de695
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d95
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e95
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049095
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea18895
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e95
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e95
		fabricloader: Fabric Loader 0.9.3+build.207
		inventoryprofiles: Inventory Profiles 0.4.2
		litematica: Litematica 0.0.0-dev.20200913.215807
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		minecraft: Minecraft 1.16.3
		minihud: MiniHUD 0.19.0-dev.20200912.222204
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.14.6+build.31
		optifabric: OptiFabric 1.6.4
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		roughlyenoughitems: Roughly Enough Items 5.4.2
		roughlyenoughitems-api: REI (API) 5.4.2
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.4.2
		roughlyenoughitems-runtime: REI (Runtime) 5.4.2
		roughlyenoughresources: Roughly Enough Resources 2.1.2
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		tweakeroo: Tweakeroo 0.10.0-dev.20200913.175041
		voxelmap: VoxelMap 1.10.11
	Launched Version: fabric-loader-0.9.3+build.207-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric/fabric-renderer-api-v1, fabric/fabric-keybindings-v0, fabric/fabricloader, fabric/inventoryprofiles, fabric/fabric-containers-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/mm, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-textures-v0, fabric/roughlyenoughresources, fabric/fabric-rendering-fluids-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-lifecycle-events-v1, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/fabric, fabric/fabric-networking-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-networking-blockentity-v0, fabric/fabric-tool-attribute-api-v1, fabric/roughlyenoughitems-runtime, fabric/fabric-renderer-indigo, fabric/roughlyenoughitems, fabric/fabric-item-api-v1, fabric/fabric-events-interaction-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-key-binding-api-v1, fabric/cloth-config2, fabric/smoothscrollingeverywhere, fabric/fabric-resource-loader-v0, fabric/autoconfig1u, fabric/fabric-content-registries-v0, fabric/fabric-tag-extensions-v0, fabric/fabric-biome-api-v1, fabric/optifabric, fabric/clear-skies, fabric/fabric-registry-sync-v0, fabric/fabric-mining-levels-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-models-v0, fabric/fabric-item-groups-v0, fabric/fabric-object-builders-v0, file/VanillaTweaks_r488145.zip, file/Lum.zip, fabric/carpet, fabric/carpet-extra, fabric/litematica (incompatible), fabric/malilib (incompatible), fabric/minihud (incompatible), fabric/modmenu, fabric/tweakeroo (incompatible), fabric/voxelmap (incompatible), file/VoxelMap-ThinFrame-pf5_2.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 452.06
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

</details>

**Comment by arxenix** [comment]
Interesting, thanks for the report. Will be looking into it this weekend.
